import { PostAudience, PostType, UserVerifyStatus } from '@/constants/enums'
import { PostReqBody } from '@/models/requests/Posts.requests'
import { RegisterReqBody } from '@/models/requests/Users.requests'
import User from '@/models/schemas/User.schema'
import databaseServices from '@/services/database.services'
import { faker } from '@faker-js/faker'
import { ObjectId } from 'mongodb'
import { hasPassword } from './crypto'
import Follower from '@/models/schemas/Follower.schema'
import postsService from '@/services/posts.services'

const PASSWORD = '123456789aA@'
const MY_ID = '65882c5c5339374babe51089'
const USER_COUNT = 941

const createRandomUser = () => {
  const user: RegisterReqBody = {
    name: faker.internet.displayName(),
    email: faker.internet.email(),
    password: PASSWORD,
    confirm_password: PASSWORD,
    date_of_birth: faker.date.past().toISOString()
  }
  return user
}

const avatars = [
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa007.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa006.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa005.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa004.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa003.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa002.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa001.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa000.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1700.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1701.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1702.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1703.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1704.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1705.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1706.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1707.jpg',
  'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1708.jpg'
]

const medias = [
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa000.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa001.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa002.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa003.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa004.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa005.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa006.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/458d46cecd6cbdb89d76fa007.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1700.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1701.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1702.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1703.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1704.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1705.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1706.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1707.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/24b979af04028de57252c1708.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/images/96576bdc84472b12bb8352200.jpg',
    type: 0
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/videos/8fd5f09eb5b690795f0a5ee00.mp4',
    type: 1
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/videos/8fd5f09eb5b690795f0a5ee01.mp4',
    type: 1
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/videos/8fd5f09eb5b690795f0a5ee02.mp4',
    type: 1
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/videos/8fd5f09eb5b690795f0a5ee03.mp4',
    type: 1
  },
  {
    url: 'https://social-media-ap-southeast-1.s3.ap-southeast-1.amazonaws.com/videos/8fd5f09eb5b690795f0a5ee04.mp4',
    type: 1
  }
]

const names = [
  { username: 'hoangthanhnhat', name: 'Hoàng Thành Nhật' },
  { username: 'vuvantan', name: 'Vũ Văn Tân' },
  { username: 'buithudieu', name: 'Bùi Thu Diệu' },
  { username: 'nguyentiennhat', name: 'Nguyễn Tiến Nhật' },
  { username: 'nguyendungthien', name: 'Nguyễn Dũng Thiên' },
  { username: 'buiyencong', name: 'Bùi Yến Công' },
  { username: 'vuhieudieu', name: 'Vũ Hiếu Diệu' },
  { username: 'tranduyendat', name: 'Trần Duyên Đạt' },
  { username: 'hoanganhnhat', name: 'Hoàng Anh Nhật' },
  { username: 'phamthinhhai', name: 'Phạm Thịnh Hải' },
  { username: 'tranthuycong', name: 'Trần Thuý Công' },
  { username: 'hotuandong', name: 'Hồ Tuấn Đông' },
  { username: 'tranhangtam', name: 'Trần Hằng Tâm' },
  { username: 'hoangngocquoc', name: 'Hoàng Ngọc Quốc' },
  { username: 'nguyenhuongtruong', name: 'Nguyễn Hương Trường' },
  { username: 'dangyenmai', name: 'Đặng Yến Mai' },
  { username: 'lehaitrang', name: 'Lê Hải Trang' },
  { username: 'hoangducnhat', name: 'Hoàng Đức Nhật' },
  { username: 'lethuytruong', name: 'Lê Thúy Trường' },
  { username: 'daothudat', name: 'Đào Thu Đạt' },
  { username: 'hothanhduy', name: 'Hồ Thành Duy' },
  { username: 'buihuymai', name: 'Bùi Huy Mai' },
  { username: 'hoanghangmai', name: 'Hoàng Hằng Mai' },
  { username: 'vuduyenkien', name: 'Vũ Duyên Kiên' },
  { username: 'tranhuytam', name: 'Trần Huy Tâm' },
  { username: 'buitrangnhat', name: 'Bùi Trang Nhật' },
  { username: 'danghangtrang', name: 'Đặng Hằng Trang' },
  { username: 'hohailam', name: 'Hồ Hải Lâm' },
  { username: 'phanminhhan', name: 'Phan Minh Hân' },
  { username: 'hoangkhoaviet', name: 'Hoàng Khoa Việt' },
  { username: 'danghieudieu', name: 'Đặng Hiếu Diệu' },
  { username: 'phamhungthinh', name: 'Phạm Hùng Thịnh' },
  { username: 'phamtrungnhat', name: 'Phạm Trung Nhật' },
  { username: 'dangtientuan', name: 'Đặng Tiến Tuấn' },
  { username: 'nguyenhuyenkien', name: 'Nguyễn Huyền Kiên' },
  { username: 'danghungthuy', name: 'Đặng Hùng Thúy' },
  { username: 'vunhutam', name: 'Vũ Như Tâm' },
  { username: 'phamthuydat', name: 'Phạm Thúy Đạt' },
  { username: 'tranhieumai', name: 'Trần Hiếu Mai' },
  { username: 'vungochan', name: 'Vũ Ngọc Hân' },
  { username: 'daominhdieu', name: 'Đào Minh Diệu' },
  { username: 'dangtrunghai', name: 'Đặng Trung Hải' },
  { username: 'buidunghien', name: 'Bùi Dũng Hiền' },
  { username: 'phanhungdieu', name: 'Phan Hùng Diệu' },
  { username: 'hothanhkien', name: 'Hồ Thành Kiên' },
  { username: 'hohungviet', name: 'Hồ Hùng Việt' },
  { username: 'vutuantrang', name: 'Vũ Tuấn Trang' },
  { username: 'vulinhtuan', name: 'Vũ Linh Tuấn' },
  { username: 'nguyenhuongtrang', name: 'Nguyễn Hương Trang' },
  { username: 'letienhuong', name: 'Lê Tiến Hương' },
  { username: 'nguyenhunghoan', name: 'Nguyễn Hùng Hoàn' },
  { username: 'danghungnam', name: 'Đặng Hùng Nam' },
  { username: 'nguyenkhoahung', name: 'Nguyễn Khoa Hùng' },
  { username: 'vuthuytrang', name: 'Vũ Thuý Trang' },
  { username: 'hohaihuong', name: 'Hồ Hải Hương' },
  { username: 'buihuonghien', name: 'Bùi Hương Hiền' },
  { username: 'hoangthaihuong', name: 'Hoàng Thái Hương' },
  { username: 'buithuyphu', name: 'Bùi Thúy Phú' },
  { username: 'phanngoctruong', name: 'Phan Ngọc Trường' },
  { username: 'dangdungthien', name: 'Đặng Dũng Thiên' },
  { username: 'phanthuydat', name: 'Phan Thuý Đạt' },
  { username: 'phanhungphu', name: 'Phan Hùng Phú' },
  { username: 'daothutam', name: 'Đào Thu Tâm' },
  { username: 'trantrungthuy', name: 'Trần Trung Thúy' },
  { username: 'tranngantan', name: 'Trần Ngân Tân' },
  { username: 'danghuongquoc', name: 'Đặng Hương Quốc' },
  { username: 'buiyenmai', name: 'Bùi Yến Mai' },
  { username: 'phantunghuong', name: 'Phan Tùng Hương' },
  { username: 'nguyenhuyenhuong', name: 'Nguyễn Huyền Hương' },
  { username: 'dangmaihien', name: 'Đặng Mai Hiền' },
  { username: 'buihungthien', name: 'Bùi Hùng Thiên' },
  { username: 'nguyenhaidieu', name: 'Nguyễn Hải Diệu' },
  { username: 'phannhuthuy', name: 'Phan Như Thúy' },
  { username: 'phanmaihien', name: 'Phan Mai Hiền' },
  { username: 'daodunghuong', name: 'Đào Dũng Hương' },
  { username: 'hoanghuytan', name: 'Hoàng Huy Tân' },
  { username: 'daothuduy', name: 'Đào Thu Duy' },
  { username: 'lequocnam', name: 'Lê Quốc Nam' },
  { username: 'danglinhtan', name: 'Đặng Linh Tân' },
  { username: 'hoangmaikhoi', name: 'Hoàng Mai Khôi' },
  { username: 'dangthainhat', name: 'Đặng Thái Nhật' },
  { username: 'hoangthuytuan', name: 'Hoàng Thuý Tuấn' },
  { username: 'hoangmaitam', name: 'Hoàng Mai Tâm' },
  { username: 'phammaithuy', name: 'Phạm Mai Thúy' },
  { username: 'phanducdieu', name: 'Phan Đức Diệu' },
  { username: 'buidunghung', name: 'Bùi Dũng Hùng' },
  { username: 'buiminhhai', name: 'Bùi Minh Hải' },
  { username: 'vutungmai', name: 'Vũ Tùng Mai' },
  { username: 'dangdunghuong', name: 'Đặng Dũng Hương' },
  { username: 'honganhan', name: 'Hồ Ngân Hân' },
  { username: 'buitienhai', name: 'Bùi Tiến Hải' },
  { username: 'phamnhutien', name: 'Phạm Như Tiến' },
  { username: 'hotrangtu', name: 'Hồ Trang Tú' },
  { username: 'nguyenyentuan', name: 'Nguyễn Yến Tuấn' },
  { username: 'phamhuyenthuy', name: 'Phạm Huyền Thúy' },
  { username: 'hoangthutam', name: 'Hoàng Thu Tâm' },
  { username: 'danglinhdieu', name: 'Đặng Linh Diệu' },
  { username: 'honganmai', name: 'Hồ Ngân Mai' },
  { username: 'danghunghuong', name: 'Đặng Hùng Hương' },
  { username: 'nguyenhoathinh', name: 'Nguyễn Hòa Thịnh' },
  { username: 'daohieudieu', name: 'Đào Hiếu Diệu' },
  { username: 'vutungnhat', name: 'Vũ Tùng Nhật' },
  { username: 'tranhuyenngan', name: 'Trần Huyền Ngân' },
  { username: 'leyennam', name: 'Lê Yến Nam' },
  { username: 'phamngoclam', name: 'Phạm Ngọc Lâm' },
  { username: 'phamtuantrang', name: 'Phạm Tuấn Trang' },
  { username: 'trantuanhieu', name: 'Trần Tuấn Hiếu' },
  { username: 'hoanghaitrang', name: 'Hoàng Hải Trang' },
  { username: 'buinhumai', name: 'Bùi Như Mai' },
  { username: 'nguyenhieutam', name: 'Nguyễn Hiếu Tâm' },
  { username: 'nguyenthuymai', name: 'Nguyễn Thuý Mai' },
  { username: 'tranhuyhuong', name: 'Trần Huy Hương' },
  { username: 'daominhthuy', name: 'Đào Minh Thúy' },
  { username: 'vuhuyenmai', name: 'Vũ Huyền Mai' },
  { username: 'daotrunghieu', name: 'Đào Trung Hiếu' },
  { username: 'phamhuonghien', name: 'Phạm Hương Hiền' },
  { username: 'phamvanmai', name: 'Phạm Văn Mai' },
  { username: 'buitungthuy', name: 'Bùi Tùng Thúy' },
  { username: 'hohieuhuong', name: 'Hồ Hiếu Hương' },
  { username: 'vutrunghieu', name: 'Vũ Trung Hiếu' },
  { username: 'lethuydieu', name: 'Lê Thúy Diệu' },
  { username: 'daohaiminh', name: 'Đào Hải Minh' },
  { username: 'phamvantien', name: 'Phạm Văn Tiến' },
  { username: 'phamminhtam', name: 'Phạm Minh Tâm' },
  { username: 'dangtrungmai', name: 'Đặng Trung Mai' },
  { username: 'hohuytan', name: 'Hồ Huy Tân' },
  { username: 'hoangyentrang', name: 'Hoàng Yến Trang' },
  { username: 'vuhunghuong', name: 'Vũ Hùng Hương' },
  { username: 'hohangngan', name: 'Hồ Hằng Ngân' },
  { username: 'danghungtam', name: 'Đặng Hùng Tâm' },
  { username: 'tranphuduy', name: 'Trần Phú Duy' },
  { username: 'phamquocdieu', name: 'Phạm Quốc Diệu' },
  { username: 'lemaimai', name: 'Lê Mai Mai' },
  { username: 'nguyenlinhtam', name: 'Nguyễn Linh Tâm' },
  { username: 'hoangthinhduy', name: 'Hoàng Thịnh Duy' },
  { username: 'danghaitrang', name: 'Đặng Hải Trang' },
  { username: 'buituanthuy', name: 'Bùi Tuấn Thúy' },
  { username: 'nguyentrunghien', name: 'Nguyễn Trung Hiền' },
  { username: 'nguyenhaiduy', name: 'Nguyễn Hải Duy' },
  { username: 'phanthanhdat', name: 'Phan Thành Đạt' },
  { username: 'trantrungmai', name: 'Trần Trung Mai' },
  { username: 'nguyenminhtam', name: 'Nguyễn Minh Tâm' },
  { username: 'phanhaituan', name: 'Phan Hải Tuấn' },
  { username: 'hoangtrangtrang', name: 'Hoàng Trang Trang' },
  { username: 'hoangdungtrang', name: 'Hoàng Dũng Trang' },
  { username: 'vuthucong', name: 'Vũ Thu Công' },
  { username: 'daohailam', name: 'Đào Hải Lâm' },
  { username: 'danghuyenngan', name: 'Đặng Huyền Ngân' },
  { username: 'buingockien', name: 'Bùi Ngọc Kiên' },
  { username: 'nguyenthuyphu', name: 'Nguyễn Thúy Phú' },
  { username: 'buihuykhoi', name: 'Bùi Huy Khôi' },
  { username: 'buihungtruong', name: 'Bùi Hùng Trường' },
  { username: 'phanhuongduy', name: 'Phan Hương Duy' },
  { username: 'hoangkhoanhat', name: 'Hoàng Khoa Nhật' },
  { username: 'lethanhtung', name: 'Lê Thành Tùng' },
  { username: 'hoanghoatrang', name: 'Hoàng Hòa Trang' },
  { username: 'tranhuythuy', name: 'Trần Huy Thúy' },
  { username: 'hohuytu', name: 'Hồ Huy Tú' },
  { username: 'lehungcong', name: 'Lê Hùng Công' },
  { username: 'nguyenhungdong', name: 'Nguyễn Hùng Đông' },
  { username: 'tranthinhthuy', name: 'Trần Thịnh Thúy' },
  { username: 'hoangminhhai', name: 'Hoàng Minh Hải' },
  { username: 'daovannhat', name: 'Đào Văn Nhật' },
  { username: 'hothudat', name: 'Hồ Thu Đạt' },
  { username: 'phamphuhoan', name: 'Phạm Phú Hoàn' },
  { username: 'hokhoakhoi', name: 'Hồ Khoa Khôi' },
  { username: 'nguyennganthuy', name: 'Nguyễn Ngân Thúy' },
  { username: 'daomaitrang', name: 'Đào Mai Trang' },
  { username: 'dangtrangthuy', name: 'Đặng Trang Thúy' },
  { username: 'phamngandong', name: 'Phạm Ngân Đông' },
  { username: 'lethinhthuy', name: 'Lê Thịnh Thúy' },
  { username: 'phamyennhat', name: 'Phạm Yến Nhật' },
  { username: 'daohuongngan', name: 'Đào Hương Ngân' },
  { username: 'trantuananh', name: 'Trần Tuấn Anh' },
  { username: 'hodungquoc', name: 'Hồ Dũng Quốc' },
  { username: 'danghuyentrang', name: 'Đặng Huyền Trang' },
  { username: 'vukhoadieu', name: 'Vũ Khoa Diệu' },
  { username: 'buihuydieu', name: 'Bùi Huy Diệu' },
  { username: 'nguyenhoanhat', name: 'Nguyễn Hòa Nhật' },
  { username: 'hoquocdieu', name: 'Hồ Quốc Diệu' },
  { username: 'vuyentung', name: 'Vũ Yến Tùng' },
  { username: 'nguyenhieutu', name: 'Nguyễn Hiếu Tú' },
  { username: 'hohuyviet', name: 'Hồ Huy Việt' },
  { username: 'phanhuonghieu', name: 'Phan Hương Hiếu' },
  { username: 'buihungtung', name: 'Bùi Hùng Tùng' },
  { username: 'leminhthinh', name: 'Lê Minh Thịnh' },
  { username: 'lephudieu', name: 'Lê Phú Diệu' },
  { username: 'nguyenthinhtien', name: 'Nguyễn Thịnh Tiến' },
  { username: 'holinhnhat', name: 'Hồ Linh Nhật' },
  { username: 'hoanghuyentam', name: 'Hoàng Huyền Tâm' },
  { username: 'vutiendieu', name: 'Vũ Tiến Diệu' },
  { username: 'phamthaimai', name: 'Phạm Thái Mai' },
  { username: 'daodungnha', name: 'Đào Dũng Nhã' },
  { username: 'lehangthuy', name: 'Lê Hằng Thúy' },
  { username: 'buiphudieu', name: 'Bùi Phú Diệu' },
  { username: 'nguyenyenphu', name: 'Nguyễn Yến Phú' },
  { username: 'vuthutuan', name: 'Vũ Thu Tuấn' },
  { username: 'honhukien', name: 'Hồ Như Kiên' },
  { username: 'hoangtientrang', name: 'Hoàng Tiến Trang' },
  { username: 'buikhoanhat', name: 'Bùi Khoa Nhật' },
  { username: 'levanthinh', name: 'Lê Văn Thịnh' },
  { username: 'hothanhviet', name: 'Hồ Thành Việt' },
  { username: 'danglinhmai', name: 'Đặng Linh Mai' },
  { username: 'phanthuthuy', name: 'Phan Thu Thúy' },
  { username: 'phannhutrang', name: 'Phan Như Trang' },
  { username: 'hoanghieumai', name: 'Hoàng Hiếu Mai' },
  { username: 'daothuyanh', name: 'Đào Thúy Anh' },
  { username: 'letienhieu', name: 'Lê Tiến Hiếu' },
  { username: 'nguyendungnha', name: 'Nguyễn Dũng Nhã' },
  { username: 'phanhuyennhat', name: 'Phan Huyền Nhật' },
  { username: 'vuquoctrang', name: 'Vũ Quốc Trang' },
  { username: 'holinhtrang', name: 'Hồ Linh Trang' },
  { username: 'phanhuongtam', name: 'Phan Hương Tâm' },
  { username: 'nguyenhaiduong', name: 'Nguyễn Hải Dương' },
  { username: 'daothaitam', name: 'Đào Thái Tâm' },
  { username: 'vunganhuong', name: 'Vũ Ngân Hương' },
  { username: 'vuhuyentrang', name: 'Vũ Huyền Trang' },
  { username: 'daoanhngan', name: 'Đào Anh Ngân' },
  { username: 'phamminhthinh', name: 'Phạm Minh Thịnh' },
  { username: 'hokhoadat', name: 'Hồ Khoa Đạt' },
  { username: 'phamngantruong', name: 'Phạm Ngân Trường' },
  { username: 'daoyendieu', name: 'Đào Yến Diệu' },
  { username: 'vuyenanh', name: 'Vũ Yến Anh' },
  { username: 'danghaihien', name: 'Đặng Hải Hiền' },
  { username: 'nguyenquockhoi', name: 'Nguyễn Quốc Khôi' },
  { username: 'vuhoanhat', name: 'Vũ Hòa Nhật' },
  { username: 'vuhuongdieu', name: 'Vũ Hương Diệu' },
  { username: 'vuhuyenhien', name: 'Vũ Huyền Hiền' },
  { username: 'vuhaitruong', name: 'Vũ Hải Trường' },
  { username: 'hotungtam', name: 'Hồ Tùng Tâm' },
  { username: 'dangdungdong', name: 'Đặng Dũng Đông' },
  { username: 'dangdungnhat', name: 'Đặng Dũng Nhật' },
  { username: 'nguyenhieunha', name: 'Nguyễn Hiếu Nhã' },
  { username: 'vuhoathinh', name: 'Vũ Hòa Thịnh' },
  { username: 'hoangthinhhai', name: 'Hoàng Thịnh Hải' },
  { username: 'nguyenhoahan', name: 'Nguyễn Hòa Hàn' },
  { username: 'vungochuong', name: 'Vũ Ngọc Hương' },
  { username: 'vudungtuan', name: 'Vũ Dũng Tuấn' },
  { username: 'phamthitrang', name: 'Phạm Thị Trang' },
  { username: 'tranhangthinh', name: 'Trần Hằng Thịnh' },
  { username: 'vuduyendieu', name: 'Vũ Duyên Diệu' },
  { username: 'phamthanhhan', name: 'Phạm Thành Hân' },
  { username: 'hohunghan', name: 'Hồ Hùng Hân' },
  { username: 'phanlinhthuy', name: 'Phan Linh Thúy' },
  { username: 'lethaitam', name: 'Lê Thái Tâm' },
  { username: 'dangthuyviet', name: 'Đặng Thuý Việt' },
  { username: 'vutrunghuong', name: 'Vũ Trung Hương' },
  { username: 'leanhthuy', name: 'Lê Anh Thúy' },
  { username: 'buituanminh', name: 'Bùi Tuấn Minh' },
  { username: 'tranhangdieu', name: 'Trần Hằng Diệu' },
  { username: 'nguyenthuytam', name: 'Nguyễn Thuý Tâm' },
  { username: 'nguyentungnam', name: 'Nguyễn Tùng Nam' },
  { username: 'daomaingan', name: 'Đào Mai Ngân' },
  { username: 'hohuyhieu', name: 'Hồ Huy Hiếu' },
  { username: 'hoangtienthinh', name: 'Hoàng Tiến Thịnh' },
  { username: 'dangvantrang', name: 'Đặng Văn Trang' },
  { username: 'nguyenhungcong', name: 'Nguyễn Hùng Công' },
  { username: 'hohaithuy', name: 'Hồ Hải Thúy' },
  { username: 'danghuongtam', name: 'Đặng Hương Tâm' },
  { username: 'hovanphu', name: 'Hồ Văn Phú' },
  { username: 'vungandieu', name: 'Vũ Ngân Diệu' },
  { username: 'nguyentuannhat', name: 'Nguyễn Tuấn Nhật' },
  { username: 'buiminhthuy', name: 'Bùi Minh Thúy' },
  { username: 'buihuyentien', name: 'Bùi Huyền Tiến' },
  { username: 'phanthinhtruong', name: 'Phan Thịnh Trường' },
  { username: 'hohuythien', name: 'Hồ Huy Thiên' },
  { username: 'dangminhmai', name: 'Đặng Minh Mai' },
  { username: 'daohangtan', name: 'Đào Hằng Tân' },
  { username: 'vutienhien', name: 'Vũ Tiến Hiền' },
  { username: 'phamminhhieu', name: 'Phạm Minh Hiếu' },
  { username: 'phammaitrang', name: 'Phạm Mai Trang' },
  { username: 'lethaitrang', name: 'Lê Thái Trang' },
  { username: 'phamhungthuy', name: 'Phạm Hùng Thúy' },
  { username: 'buithaihieu', name: 'Bùi Thái Hiếu' },
  { username: 'nguyenminhduy', name: 'Nguyễn Minh Duy' },
  { username: 'phantunghien', name: 'Phan Tùng Hiền' },
  { username: 'buitungtrang', name: 'Bùi Tùng Trang' },
  { username: 'vuhuongcong', name: 'Vũ Hương Công' },
  { username: 'hoanghuonghien', name: 'Hoàng Hương Hiền' },
  { username: 'vuducnhat', name: 'Vũ Đức Nhật' },
  { username: 'phamhaithuy', name: 'Phạm Hải Thúy' },
  { username: 'buihaihan', name: 'Bùi Hải Hân' },
  { username: 'daomaikien', name: 'Đào Mai Kiên' },
  { username: 'nguyentuandieu', name: 'Nguyễn Tuấn Diệu' },
  { username: 'hothithinh', name: 'Hồ Thị Thịnh' },
  { username: 'nguyenlinhhan', name: 'Nguyễn Linh Hân' },
  { username: 'dangdungmy', name: 'Đặng Dũng Mỹ' },
  { username: 'phamdungmai', name: 'Phạm Dũng Mai' },
  { username: 'phanhungmai', name: 'Phan Hùng Mai' },
  { username: 'hoangkhoatrang', name: 'Hoàng Khoa Trang' },
  { username: 'dangthaitam', name: 'Đặng Thái Tâm' },
  { username: 'hoangminhtam', name: 'Hoàng Minh Tâm' },
  { username: 'nguyenthutu', name: 'Nguyễn Thu Tú' },
  { username: 'buivanthuy', name: 'Bùi Văn Thúy' },
  { username: 'hooaihuong', name: 'Hồ Oải Hương' },
  { username: 'vuhoahuong', name: 'Vũ Hòa Hương' },
  { username: 'trandungdieu', name: 'Trần Dũng Diệu' },
  { username: 'daotungquoc', name: 'Đào Tùng Quốc' },
  { username: 'danghuycong', name: 'Đặng Huy Công' },
  { username: 'daokhoadat', name: 'Đào Khoa Đạt' },
  { username: 'leyendieu', name: 'Lê Yến Diệu' },
  { username: 'phanhoanam', name: 'Phan Hòa Nam' },
  { username: 'vudungnhat', name: 'Vũ Dũng Nhật' },
  { username: 'phanhungtrang', name: 'Phan Hùng Trang' },
  { username: 'dangnhuhien', name: 'Đặng Như Hiền' },
  { username: 'dangtientu', name: 'Đặng Tiến Tú' },
  { username: 'nguyenthuylam', name: 'Nguyễn Thúy Lâm' },
  { username: 'daominhanh', name: 'Đào Minh Anh' },
  { username: 'nguyenphutam', name: 'Nguyễn Phú Tâm' },
  { username: 'danghungphu', name: 'Đặng Hùng Phú' },
  { username: 'phanminhtam', name: 'Phan Minh Tâm' },
  { username: 'dangthaihien', name: 'Đặng Thái Hiền' },
  { username: 'phamhainhat', name: 'Phạm Hải Nhật' },
  { username: 'daohuongnha', name: 'Đào Hương Nhã' },
  { username: 'nguyendungdieu', name: 'Nguyễn Dũng Diệu' },
  { username: 'daotungdieu', name: 'Đào Tùng Diệu' },
  { username: 'hotrangtrang', name: 'Hồ Trang Trang' },
  { username: 'vuminhhien', name: 'Vũ Minh Hiền' },
  { username: 'dangnganlam', name: 'Đặng Ngân Lâm' },
  { username: 'nguyenanhtrang', name: 'Nguyễn Anh Trang' },
  { username: 'phanminhmai', name: 'Phan Minh Mai' },
  { username: 'hohuyenthuy', name: 'Hồ Huyền Thúy' },
  { username: 'phamhoatien', name: 'Phạm Hòa Tiến' },
  { username: 'nguyenhoanha', name: 'Nguyễn Hòa Nhã' },
  { username: 'tranmaihuong', name: 'Trần Mai Hương' },
  { username: 'phamtuankien', name: 'Phạm Tuấn Kiên' },
  { username: 'daohangquoc', name: 'Đào Hằng Quốc' },
  { username: 'buimaiphu', name: 'Bùi Mai Phú' },
  { username: 'nguyenthinhkhoi', name: 'Nguyễn Thịnh Khôi' },
  { username: 'hothuydieu', name: 'Hồ Thuý Diệu' },
  { username: 'phamlinhquoc', name: 'Phạm Linh Quốc' },
  { username: 'nguyenthinhanh', name: 'Nguyễn Thịnh Anh' },
  { username: 'buitrungdong', name: 'Bùi Trung Đông' },
  { username: 'buithuytam', name: 'Bùi Thúy Tâm' },
  { username: 'buiphucong', name: 'Bùi Phú Công' },
  { username: 'lehuytrang', name: 'Lê Huy Trang' },
  { username: 'nguyenthidieu', name: 'Nguyễn Thị Diệu' },
  { username: 'buihoadieu', name: 'Bùi Hòa Diệu' },
  { username: 'phamnhucong', name: 'Phạm Như Công' },
  { username: 'dangtuananh', name: 'Đặng Tuấn Anh' },
  { username: 'hoangthaithuy', name: 'Hoàng Thái Thúy' },
  { username: 'vuanhdieu', name: 'Vũ Anh Diệu' },
  { username: 'hoangtuannhat', name: 'Hoàng Tuấn Nhật' },
  { username: 'nguyenthuytim', name: 'Nguyễn Thuý Tim' },
  { username: 'lenganviet', name: 'Lê Ngân Việt' },
  { username: 'nguyenyenhai', name: 'Nguyễn Yến Hải' },
  { username: 'hotrangkhoi', name: 'Hồ Trang Khôi' },
  { username: 'lehuonghai', name: 'Lê Hương Hải' },
  { username: 'hoyenphu', name: 'Hồ Yến Phú' },
  { username: 'phannhungan', name: 'Phan Như Ngân' },
  { username: 'lethaiphu', name: 'Lê Thái Phú' },
  { username: 'hoangthuymai', name: 'Hoàng Thuý Mai' },
  { username: 'phantuantam', name: 'Phan Tuấn Tâm' },
  { username: 'danglinhminh', name: 'Đặng Linh Minh' },
  { username: 'daothuytien', name: 'Đào Thúy Tiến' },
  { username: 'phanhangtien', name: 'Phan Hằng Tiến' },
  { username: 'nguyenngoctam', name: 'Nguyễn Ngọc Tâm' },
  { username: 'dangthanhtam', name: 'Đặng Thành Tâm' },
  { username: 'tranminhhuong', name: 'Trần Minh Hương' },
  { username: 'daothinhdieu', name: 'Đào Thịnh Diệu' },
  { username: 'lethinhtam', name: 'Lê Thịnh Tâm' },
  { username: 'tranhangthien', name: 'Trần Hằng Thiên' },
  { username: 'dangthinhlam', name: 'Đặng Thịnh Lâm' },
  { username: 'phanhaitung', name: 'Phan Hải Tùng' },
  { username: 'phanquochai', name: 'Phan Quốc Hải' },
  { username: 'buihieumai', name: 'Bùi Hiếu Mai' },
  { username: 'nguyenhuongnhat', name: 'Nguyễn Hương Nhật' },
  { username: 'nguyenthaitrang', name: 'Nguyễn Thái Trang' },
  { username: 'lethuyquoc', name: 'Lê Thuý Quốc' },
  { username: 'hoanghungtrang', name: 'Hoàng Hùng Trang' },
  { username: 'buituantrang', name: 'Bùi Tuấn Trang' },
  { username: 'dangtienkhoi', name: 'Đặng Tiến Khôi' },
  { username: 'phandungdong', name: 'Phan Dũng Đông' },
  { username: 'phamdunghai', name: 'Phạm Dũng Hải' },
  { username: 'hothuquoc', name: 'Hồ Thu Quốc' },
  { username: 'phanthihien', name: 'Phan Thị Hiền' },
  { username: 'phamphuhien', name: 'Phạm Phú Hiền' },
  { username: 'phanthuynam', name: 'Phan Thúy Nam' },
  { username: 'vuthuyviet', name: 'Vũ Thúy Việt' },
  { username: 'vuhoakien', name: 'Vũ Hòa Kiên' },
  { username: 'hoangnhuduy', name: 'Hoàng Như Duy' },
  { username: 'dangtienhien', name: 'Đặng Tiến Hiền' },
  { username: 'vuthuthuy', name: 'Vũ Thu Thúy' },
  { username: 'vuvanminh', name: 'Vũ Văn Minh' },
  { username: 'dangngocnhat', name: 'Đặng Ngọc Nhật' },
  { username: 'lenganhieu', name: 'Lê Ngân Hiếu' },
  { username: 'buiduyenkien', name: 'Bùi Duyên Kiên' },
  { username: 'hoangquocnha', name: 'Hoàng Quốc Nhã' },
  { username: 'phantrangdong', name: 'Phan Trang Đông' },
  { username: 'trankhoathuy', name: 'Trần Khoa Thúy' },
  { username: 'vutienquoc', name: 'Vũ Tiến Quốc' },
  { username: 'phamducdieu', name: 'Phạm Đức Diệu' },
  { username: 'dangthuphu', name: 'Đặng Thu Phú' },
  { username: 'buihunghuong', name: 'Bùi Hùng Hương' },
  { username: 'hoangthailam', name: 'Hoàng Thái Lâm' },
  { username: 'vumaiphu', name: 'Vũ Mai Phú' },
  { username: 'nguyentientan', name: 'Nguyễn Tiến Tân' },
  { username: 'tranphuphu', name: 'Trần Phú Phú' },
  { username: 'nguyenthaikien', name: 'Nguyễn Thái Kiên' },
  { username: 'dangngocdieu', name: 'Đặng Ngọc Diệu' },
  { username: 'phanvannam', name: 'Phan Văn Nam' },
  { username: 'hoangduyennhat', name: 'Hoàng Duyên Nhật' },
  { username: 'buithuydieu', name: 'Bùi Thuý Diệu' },
  { username: 'dangminhtu', name: 'Đặng Minh Tú' },
  { username: 'vuthinhanh', name: 'Vũ Thịnh Anh' },
  { username: 'phamhunghung', name: 'Phạm Hùng Hùng' },
  { username: 'dangtranglam', name: 'Đặng Trang Lâm' },
  { username: 'lengocnhat', name: 'Lê Ngọc Nhật' },
  { username: 'vuminhtuan', name: 'Vũ Minh Tuấn' },
  { username: 'dangphunha', name: 'Đặng Phú Nhã' },
  { username: 'dangphuanh', name: 'Đặng Phú Anh' },
  { username: 'hoangtrunghung', name: 'Hoàng Trung Hùng' },
  { username: 'lehoamai', name: 'Lê Hòa Mai' },
  { username: 'nguyenvandieu', name: 'Nguyễn Văn Diệu' },
  { username: 'trankhoakien', name: 'Trần Khoa Kiên' },
  { username: 'nguyenhaingan', name: 'Nguyễn Hải Ngân' },
  { username: 'hothanhtam', name: 'Hồ Thành Tâm' },
  { username: 'hohangmai', name: 'Hồ Hằng Mai' },
  { username: 'phantuandong', name: 'Phan Tuấn Đông' },
  { username: 'hovandieu', name: 'Hồ Văn Diệu' },
  { username: 'trananhtam', name: 'Trần Anh Tâm' },
  { username: 'phamnhudieu', name: 'Phạm Như Diệu' },
  { username: 'daohungnhat', name: 'Đào Hùng Nhật' },
  { username: 'phanhoathuy', name: 'Phan Hòa Thúy' },
  { username: 'buitientam', name: 'Bùi Tiến Tâm' },
  { username: 'phantienthinh', name: 'Phan Tiến Thịnh' },
  { username: 'nguyenhunghuong', name: 'Nguyễn Hùng Hương' },
  { username: 'tranthaihan', name: 'Trần Thái Hân' },
  { username: 'buithanhnhat', name: 'Bùi Thành Nhật' },
  { username: 'hoangtuanhan', name: 'Hoàng Tuấn Hân' },
  { username: 'phamtrangnhat', name: 'Phạm Trang Nhật' },
  { username: 'daohieuthuy', name: 'Đào Hiếu Thúy' },
  { username: 'vuminhngan', name: 'Vũ Minh Ngân' },
  { username: 'dangdungkhoi', name: 'Đặng Dũng Khôi' },
  { username: 'phanquocnhat', name: 'Phan Quốc Nhật' },
  { username: 'hoangvantam', name: 'Hoàng Văn Tâm' },
  { username: 'buihaitu', name: 'Bùi Hải Tú' },
  { username: 'phamtrungtam', name: 'Phạm Trung Tâm' },
  { username: 'daotienhan', name: 'Đào Tiến Hân' },
  { username: 'danghoahoan', name: 'Đặng Hòa Hoàn' },
  { username: 'phamthithuy', name: 'Phạm Thị Thúy' },
  { username: 'dangquochien', name: 'Đặng Quốc Hiền' },
  { username: 'tranhoatung', name: 'Trần Hòa Tùng' },
  { username: 'daodungnhat', name: 'Đào Dũng Nhật' },
  { username: 'phamhaimai', name: 'Phạm Hải Mai' },
  { username: 'hodungphu', name: 'Hồ Dũng Phú' },
  { username: 'hoangmainam', name: 'Hoàng Mai Nam' },
  { username: 'hoangtungtrang', name: 'Hoàng Tùng Trang' },
  { username: 'hoangnhunhat', name: 'Hoàng Như Nhật' },
  { username: 'tranhaihuong', name: 'Trần Hải Hương' },
  { username: 'letrunghai', name: 'Lê Trung Hải' },
  { username: 'dangminhhoan', name: 'Đặng Minh Hoàn' },
  { username: 'vuthitam', name: 'Vũ Thị Tâm' },
  { username: 'daotrangminh', name: 'Đào Trang Minh' },
  { username: 'buihunghai', name: 'Bùi Hùng Hải' },
  { username: 'nguyenthinhviet', name: 'Nguyễn Thịnh Việt' },
  { username: 'lehaitu', name: 'Lê Hải Tú' },
  { username: 'buingannha', name: 'Bùi Ngân Nhã' },
  { username: 'daohoahoan', name: 'Đào Hòa Hoàn' },
  { username: 'danghuyennhat', name: 'Đặng Huyền Nhật' },
  { username: 'nguyenkhoathien', name: 'Nguyễn Khoa Thiên' },
  { username: 'hoduyentan', name: 'Hồ Duyên Tân' },
  { username: 'danghuydieu', name: 'Đặng Huy Diệu' },
  { username: 'hoangdungnam', name: 'Hoàng Dũng Nam' },
  { username: 'nguyentrungtam', name: 'Nguyễn Trung Tâm' },
  { username: 'tranphuhuong', name: 'Trần Phú Hương' },
  { username: 'daodungtam', name: 'Đào Dũng Tâm' },
  { username: 'nguyenquocmai', name: 'Nguyễn Quốc Mai' },
  { username: 'daoyentruong', name: 'Đào Yến Trường' },
  { username: 'daothuyhung', name: 'Đào Thuý Hùng' },
  { username: 'vulinhngan', name: 'Vũ Linh Ngân' },
  { username: 'buituantu', name: 'Bùi Tuấn Tú' },
  { username: 'phamtrangmai', name: 'Phạm Trang Mai' },
  { username: 'dangyenlam', name: 'Đặng Yến Lâm' },
  { username: 'vuhuonghien', name: 'Vũ Hương Hiền' },
  { username: 'tranthanhanh', name: 'Trần Thành Anh' },
  { username: 'lethuythuy', name: 'Lê Thúy Thúy' },
  { username: 'phamyenthuy', name: 'Phạm Yến Thúy' },
  { username: 'tranhuongthuy', name: 'Trần Hương Thúy' },
  { username: 'daothuyhieu', name: 'Đào Thúy Hiếu' },
  { username: 'daothuythien', name: 'Đào Thuý Thiên' },
  { username: 'hoangduyenthuy', name: 'Hoàng Duyên Thúy' },
  { username: 'trannhutung', name: 'Trần Như Tùng' },
  { username: 'phanhainhat', name: 'Phan Hải Nhật' },
  { username: 'vuhaithien', name: 'Vũ Hải Thiên' },
  { username: 'hohungnhat', name: 'Hồ Hùng Nhật' },
  { username: 'hoangthuydong', name: 'Hoàng Thúy Đông' },
  { username: 'daohunghuong', name: 'Đào Hùng Hương' },
  { username: 'homaiviet', name: 'Hồ Mai Việt' },
  { username: 'phanthaitrang', name: 'Phan Thái Trang' },
  { username: 'nguyenanhmai', name: 'Nguyễn Anh Mai' },
  { username: 'lethanhmai', name: 'Lê Thành Mai' },
  { username: 'phamdungnhat', name: 'Phạm Dũng Nhật' },
  { username: 'hoangngantam', name: 'Hoàng Ngân Tâm' },
  { username: 'hominhhien', name: 'Hồ Minh Hiền' },
  { username: 'daoquocthinh', name: 'Đào Quốc Thịnh' },
  { username: 'hothanhtung', name: 'Hồ Thành Tùng' },
  { username: 'dangmaithuy', name: 'Đặng Mai Thúy' },
  { username: 'buithanhtu', name: 'Bùi Thành Tú' },
  { username: 'trantuanthuy', name: 'Trần Tuấn Thúy' },
  { username: 'trantungmai', name: 'Trần Tùng Mai' },
  { username: 'hoangdungnhat', name: 'Hoàng Dũng Nhật' },
  { username: 'tranyentien', name: 'Trần Yến Tiến' },
  { username: 'lehaianh', name: 'Lê Hải Anh' },
  { username: 'nguyenyennha', name: 'Nguyễn Yến Nhã' },
  { username: 'buihuongnhat', name: 'Bùi Hương Nhật' },
  { username: 'trantrungnam', name: 'Trần Trung Nam' },
  { username: 'daoanhnam', name: 'Đào Anh Nam' },
  { username: 'nguyentrangtan', name: 'Nguyễn Trang Tân' },
  { username: 'vutienhan', name: 'Vũ Tiến Hân' },
  { username: 'phanhungthuy', name: 'Phan Hùng Thúy' },
  { username: 'vuthanhhai', name: 'Vũ Thành Hải' },
  { username: 'lephucong', name: 'Lê Phú Công' },
  { username: 'hothuytam', name: 'Hồ Thúy Tâm' },
  { username: 'tranthithuy', name: 'Trần Thị Thúy' },
  { username: 'hoangduyenmai', name: 'Hoàng Duyên Mai' },
  { username: 'danghungnhat', name: 'Đặng Hùng Nhật' },
  { username: 'vuquoctien', name: 'Vũ Quốc Tiến' },
  { username: 'phannhuthinh', name: 'Phan Như Thịnh' },
  { username: 'hophumai', name: 'Hồ Phú Mai' },
  { username: 'leminhtrang', name: 'Lê Minh Trang' },
  { username: 'hoangthinhthuy', name: 'Hoàng Thịnh Thúy' },
  { username: 'phamhuongtan', name: 'Phạm Hương Tân' },
  { username: 'phanquochuong', name: 'Phan Quốc Hương' },
  { username: 'nguyenhangmai', name: 'Nguyễn Hằng Mai' },
  { username: 'phamhoatu', name: 'Phạm Hòa Tú' },
  { username: 'homaitrang', name: 'Hồ Mai Trang' },
  { username: 'vunhumai', name: 'Vũ Như Mai' },
  { username: 'hohaihan', name: 'Hồ Hải Hân' },
  { username: 'buiyendieu', name: 'Bùi Yến Diệu' },
  { username: 'dangnhucong', name: 'Đặng Như Công' },
  { username: 'buithanhtan', name: 'Bùi Thành Tân' },
  { username: 'lehuonghan', name: 'Lê Hương Hân' },
  { username: 'buihuongtam', name: 'Bùi Hương Tâm' },
  { username: 'daoanhhai', name: 'Đào Anh Hải' },
  { username: 'vuthidieu', name: 'Vũ Thị Diệu' },
  { username: 'buitienhuong', name: 'Bùi Tiến Hương' },
  { username: 'phamhoadieu', name: 'Phạm Hòa Diệu' },
  { username: 'phanlinhtam', name: 'Phan Linh Tâm' },
  { username: 'phamthinhhieu', name: 'Phạm Thịnh Hiếu' },
  { username: 'nguyentranghan', name: 'Nguyễn Trang Hân' },
  { username: 'daothaicong', name: 'Đào Thái Công' },
  { username: 'buiphutam', name: 'Bùi Phú Tâm' },
  { username: 'hoanghangdieu', name: 'Hoàng Hằng Diệu' },
  { username: 'vuhieuthuy', name: 'Vũ Hiếu Thúy' },
  { username: 'tranhungtrang', name: 'Trần Hùng Trang' },
  { username: 'danghaianh', name: 'Đặng Hải Anh' },
  { username: 'daokhoadieu', name: 'Đào Khoa Diệu' },
  { username: 'vutungthuy', name: 'Vũ Tùng Thúy' },
  { username: 'lelinhhien', name: 'Lê Linh Hiền' },
  { username: 'daothanhphu', name: 'Đào Thành Phú' },
  { username: 'daothudieu', name: 'Đào Thu Diệu' },
  { username: 'hoangnganviet', name: 'Hoàng Ngân Việt' },
  { username: 'nguyenhieunam', name: 'Nguyễn Hiếu Nam' },
  { username: 'daotrangthuy', name: 'Đào Trang Thúy' },
  { username: 'hothimai', name: 'Hồ Thị Mai' },
  { username: 'letienhung', name: 'Lê Tiến Hùng' },
  { username: 'daoyenmai', name: 'Đào Yến Mai' },
  { username: 'hohoahien', name: 'Hồ Hòa Hiền' },
  { username: 'phamhungtan', name: 'Phạm Hùng Tân' },
  { username: 'buiquoctu', name: 'Bùi Quốc Tú' },
  { username: 'hoangminhdieu', name: 'Hoàng Minh Diệu' },
  { username: 'lehuonghieu', name: 'Lê Hương Hiếu' },
  { username: 'phanngantrang', name: 'Phan Ngân Trang' },
  { username: 'buimaidieu', name: 'Bùi Mai Diệu' },
  { username: 'nguyenngandieu', name: 'Nguyễn Ngân Diệu' },
  { username: 'lengancong', name: 'Lê Ngân Công' },
  { username: 'vuhoatam', name: 'Vũ Hòa Tâm' },
  { username: 'dangthuytam', name: 'Đặng Thuý Tâm' },
  { username: 'dangducnhat', name: 'Đặng Đức Nhật' },
  { username: 'vulinhnhat', name: 'Vũ Linh Nhật' },
  { username: 'nguyenhoatuan', name: 'Nguyễn Hòa Tuấn' },
  { username: 'hoangthitien', name: 'Hoàng Thị Tiến' },
  { username: 'leminhtruong', name: 'Lê Minh Trường' },
  { username: 'phamtienkien', name: 'Phạm Tiến Kiên' },
  { username: 'vuhangtam', name: 'Vũ Hằng Tâm' },
  { username: 'lehuymai', name: 'Lê Huy Mai' },
  { username: 'nguyenmaihuong', name: 'Nguyễn Mai Hương' },
  { username: 'phanngoctuan', name: 'Phan Ngọc Tuấn' },
  { username: 'phamhaidieu', name: 'Phạm Hải Diệu' },
  { username: 'lehanghuong', name: 'Lê Hằng Hương' },
  { username: 'buinganthuy', name: 'Bùi Ngân Thúy' },
  { username: 'hominhdieu', name: 'Hồ Minh Diệu' },
  { username: 'leduyennhat', name: 'Lê Duyên Nhật' },
  { username: 'tranduyentuan', name: 'Trần Duyên Tuấn' },
  { username: 'hoanglinhkhoi', name: 'Hoàng Linh Khôi' },
  { username: 'daotiendieu', name: 'Đào Tiến Diệu' },
  { username: 'vukhoaminh', name: 'Vũ Khoa Minh' },
  { username: 'trantrangnhat', name: 'Trần Trang Nhật' },
  { username: 'phanhunghung', name: 'Phan Hùng Hùng' },
  { username: 'lekhoathuy', name: 'Lê Khoa Thúy' },
  { username: 'vungantam', name: 'Vũ Ngân Tâm' },
  { username: 'nguyentuantruong', name: 'Nguyễn Tuấn Trường' },
  { username: 'tranngantam', name: 'Trần Ngân Tâm' },
  { username: 'vutrungmai', name: 'Vũ Trung Mai' },
  { username: 'vuhunghieu', name: 'Vũ Hùng Hiếu' },
  { username: 'hoanghuyentrang', name: 'Hoàng Huyền Trang' },
  { username: 'buidungminh', name: 'Bùi Dũng Minh' },
  { username: 'nguyentrangnha', name: 'Nguyễn Trang Nhã' },
  { username: 'dangthuyhuong', name: 'Đặng Thuý Hương' },
  { username: 'vuvandat', name: 'Vũ Văn Đạt' },
  { username: 'tranquocnam', name: 'Trần Quốc Nam' },
  { username: 'phannhumai', name: 'Phan Như Mai' },
  { username: 'danganhhoan', name: 'Đặng Anh Hoàn' },
  { username: 'tranthulam', name: 'Trần Thu Lâm' },
  { username: 'lehuongthuy', name: 'Lê Hương Thúy' },
  { username: 'lehuongduy', name: 'Lê Hương Duy' },
  { username: 'trannhutrang', name: 'Trần Như Trang' },
  { username: 'vuquocduy', name: 'Vũ Quốc Duy' },
  { username: 'nguyenduyendong', name: 'Nguyễn Duyên Đông' },
  { username: 'vuhungduy', name: 'Vũ Hùng Duy' },
  { username: 'lehuyentam', name: 'Lê Huyền Tâm' },
  { username: 'nguyenthanhlam', name: 'Nguyễn Thành Lâm' },
  { username: 'hongoctu', name: 'Hồ Ngọc Tú' },
  { username: 'vuhuyphu', name: 'Vũ Huy Phú' },
  { username: 'buithiphu', name: 'Bùi Thị Phú' },
  { username: 'nguyenhieuhieu', name: 'Nguyễn Hiếu Hiếu' },
  { username: 'phantrangduy', name: 'Phan Trang Duy' },
  { username: 'vuthanhtrang', name: 'Vũ Thành Trang' },
  { username: 'dangtuanhuong', name: 'Đặng Tuấn Hương' },
  { username: 'trantrangduy', name: 'Trần Trang Duy' },
  { username: 'hoanghieulam', name: 'Hoàng Hiếu Lâm' },
  { username: 'daomaituan', name: 'Đào Mai Tuấn' },
  { username: 'daothinhhieu', name: 'Đào Thịnh Hiếu' },
  { username: 'hoanghuydieu', name: 'Hoàng Huy Diệu' },
  { username: 'buidungdieu', name: 'Bùi Dũng Diệu' },
  { username: 'nguyentienhieu', name: 'Nguyễn Tiến Hiếu' },
  { username: 'vutrungphu', name: 'Vũ Trung Phú' },
  { username: 'phankhoadieu', name: 'Phan Khoa Diệu' },
  { username: 'vuhungthinh', name: 'Vũ Hùng Thịnh' },
  { username: 'nguyennganhai', name: 'Nguyễn Ngân Hải' },
  { username: 'lethaihien', name: 'Lê Thái Hiền' },
  { username: 'hoangvantien', name: 'Hoàng Văn Tiến' },
  { username: 'phanthuyhoan', name: 'Phan Thuý Hoàn' },
  { username: 'hovanminh', name: 'Hồ Văn Minh' },
  { username: 'phandungnhat', name: 'Phan Dũng Nhật' },
  { username: 'hoanghaihuong', name: 'Hoàng Hải Hương' },
  { username: 'danghaimai', name: 'Đặng Hải Mai' },
  { username: 'phamtienhieu', name: 'Phạm Tiến Hiếu' },
  { username: 'hoyentien', name: 'Hồ Yến Tiến' },
  { username: 'hoanghuyenthuy', name: 'Hoàng Huyền Thúy' },
  { username: 'vumaiduy', name: 'Vũ Mai Duy' },
  { username: 'dangdungtrang', name: 'Đặng Dũng Trang' },
  { username: 'nguyentuanlam', name: 'Nguyễn Tuấn Lâm' },
  { username: 'hoangthaithien', name: 'Hoàng Thái Thiên' },
  { username: 'buithuythuy', name: 'Bùi Thúy Thúy' },
  { username: 'phanhuythuy', name: 'Phan Huy Thúy' },
  { username: 'dangtuanduy', name: 'Đặng Tuấn Duy' },
  { username: 'phamhungdieu', name: 'Phạm Hùng Diệu' },
  { username: 'phanhuongtung', name: 'Phan Hương Tùng' },
  { username: 'phannganhien', name: 'Phan Ngân Hiền' },
  { username: 'holinhhien', name: 'Hồ Linh Hiền' },
  { username: 'daohuyduy', name: 'Đào Huy Duy' },
  { username: 'dangtrungtam', name: 'Đặng Trung Tâm' },
  { username: 'nguyenthunhat', name: 'Nguyễn Thu Nhật' },
  { username: 'lehoadat', name: 'Lê Hòa Đạt' },
  { username: 'phantungkien', name: 'Phan Tùng Kiên' },
  { username: 'nguyenngocminh', name: 'Nguyễn Ngọc Minh' },
  { username: 'hotuanhien', name: 'Hồ Tuấn Hiền' },
  { username: 'hoanhthuy', name: 'Hồ Anh Thúy' },
  { username: 'honganquoc', name: 'Hồ Ngân Quốc' },
  { username: 'buinganthinh', name: 'Bùi Ngân Thịnh' },
  { username: 'vuminhnha', name: 'Vũ Minh Nhã' },
  { username: 'buitungtam', name: 'Bùi Tùng Tâm' },
  { username: 'daominhmai', name: 'Đào Minh Mai' },
  { username: 'leminhviet', name: 'Lê Minh Việt' },
  { username: 'phamthainha', name: 'Phạm Thái Nhã' },
  { username: 'buithuykhoi', name: 'Bùi Thúy Khôi' },
  { username: 'danglinhhien', name: 'Đặng Linh Hiền' },
  { username: 'vuduyentruong', name: 'Vũ Duyên Trường' },
  { username: 'buihaihung', name: 'Bùi Hải Hùng' },
  { username: 'phamnganhieu', name: 'Phạm Ngân Hiếu' },
  { username: 'hoanghuythuy', name: 'Hoàng Huy Thúy' },
  { username: 'phanhieutan', name: 'Phan Hiếu Tân' },
  { username: 'hoangtienngan', name: 'Hoàng Tiến Ngân' },
  { username: 'lethinhhan', name: 'Lê Thịnh Hân' },
  { username: 'nguyennhuanh', name: 'Nguyễn Như Anh' },
  { username: 'trandungmai', name: 'Trần Dũng Mai' },
  { username: 'buiduyentam', name: 'Bùi Duyên Tâm' },
  { username: 'phanhuynhat', name: 'Phan Huy Nhật' },
  { username: 'tranhanghieu', name: 'Trần Hằng Hiếu' },
  { username: 'phamthutrang', name: 'Phạm Thu Trang' },
  { username: 'phamphulam', name: 'Phạm Phú Lâm' },
  { username: 'lehunghan', name: 'Lê Hùng Hân' },
  { username: 'dangnhudong', name: 'Đặng Như Đông' },
  { username: 'daoduyendat', name: 'Đào Duyên Đạt' },
  { username: 'phannganhuong', name: 'Phan Ngân Hương' },
  { username: 'dangtienquoc', name: 'Đặng Tiến Quốc' },
  { username: 'vuthikhoi', name: 'Vũ Thị Khôi' },
  { username: 'tranthuytrang', name: 'Trần Thúy Trang' },
  { username: 'vuhuythuy', name: 'Vũ Huy Thúy' },
  { username: 'dangtungdong', name: 'Đặng Tùng Đông' },
  { username: 'nguyenkhoadieu', name: 'Nguyễn Khoa Diệu' },
  { username: 'vuhungtu', name: 'Vũ Hùng Tú' },
  { username: 'danghaitruong', name: 'Đặng Hải Trường' },
  { username: 'letunghien', name: 'Lê Tùng Hiền' },
  { username: 'buidunghoan', name: 'Bùi Dũng Hoàn' },
  { username: 'dangthithien', name: 'Đặng Thị Thiên' },
  { username: 'daominhhai', name: 'Đào Minh Hải' },
  { username: 'vuhungviet', name: 'Vũ Hùng Việt' },
  { username: 'phankhoanam', name: 'Phan Khoa Nam' },
  { username: 'daohaiduy', name: 'Đào Hải Duy' },
  { username: 'daonhumai', name: 'Đào Như Mai' },
  { username: 'phanngoctam', name: 'Phan Ngọc Tâm' },
  { username: 'phamquockien', name: 'Phạm Quốc Kiên' },
  { username: 'dangthuhoan', name: 'Đặng Thu Hoàn' },
  { username: 'phamhuongdieu', name: 'Phạm Hương Diệu' },
  { username: 'daohaithuy', name: 'Đào Hải Thúy' },
  { username: 'daotrangcong', name: 'Đào Trang Công' },
  { username: 'phanhungkhoi', name: 'Phan Hùng Khôi' },
  { username: 'buiminhkien', name: 'Bùi Minh Kiên' },
  { username: 'nguyenthanhthuy', name: 'Nguyễn Thành Thúy' },
  { username: 'vuhuongthuy', name: 'Vũ Hương Thúy' },
  { username: 'hohuyhuong', name: 'Hồ Huy Hương' },
  { username: 'hoangthidieu', name: 'Hoàng Thị Diệu' },
  { username: 'vuquoccong', name: 'Vũ Quốc Công' },
  { username: 'vuthuyduy', name: 'Vũ Thuý Duy' },
  { username: 'tranthuytam', name: 'Trần Thúy Tâm' },
  { username: 'phanthuycong', name: 'Phan Thuý Công' },
  { username: 'daohuongcong', name: 'Đào Hương Công' },
  { username: 'phanhieudong', name: 'Phan Hiếu Đông' },
  { username: 'phamhungminh', name: 'Phạm Hùng Minh' },
  { username: 'nguyenhaithuy', name: 'Nguyễn Hải Thúy' },
  { username: 'hoduyendieu', name: 'Hồ Duyên Diệu' },
  { username: 'daohoaanh', name: 'Đào Hòa Anh' },
  { username: 'phamquoctung', name: 'Phạm Quốc Tùng' },
  { username: 'phamhungkhoi', name: 'Phạm Hùng Khôi' },
  { username: 'buitrangdieu', name: 'Bùi Trang Diệu' },
  { username: 'letiendieu', name: 'Lê Tiến Diệu' },
  { username: 'nguyenanhtruong', name: 'Nguyễn Anh Trường' },
  { username: 'hothinhdat', name: 'Hồ Thịnh Đạt' },
  { username: 'daothinhtrang', name: 'Đào Thịnh Trang' },
  { username: 'nguyenmaithuy', name: 'Nguyễn Mai Thúy' },
  { username: 'vuthuhien', name: 'Vũ Thu Hiền' },
  { username: 'phantranghan', name: 'Phan Trang Hân' },
  { username: 'daohuongnhat', name: 'Đào Hương Nhật' },
  { username: 'buihieunam', name: 'Bùi Hiếu Nam' },
  { username: 'vuminhtrang', name: 'Vũ Minh Trang' },
  { username: 'tranlinhmai', name: 'Trần Linh Mai' },
  { username: 'vuyentam', name: 'Vũ Yến Tâm' },
  { username: 'daotuantan', name: 'Đào Tuấn Tân' },
  { username: 'daohuyenthuy', name: 'Đào Huyền Thúy' },
  { username: 'leminhtan', name: 'Lê Minh Tân' },
  { username: 'leductam', name: 'Lê Đức Tâm' },
  { username: 'hohangtruong', name: 'Hồ Hằng Trường' },
  { username: 'vuhungthuy', name: 'Vũ Hùng Thúy' },
  { username: 'letrungphu', name: 'Lê Trung Phú' },
  { username: 'lethanhcong', name: 'Lê Thành Công' },
  { username: 'phamngocnhat', name: 'Phạm Ngọc Nhật' },
  { username: 'daotungmai', name: 'Đào Tùng Mai' },
  { username: 'lethuytam', name: 'Lê Thúy Tâm' },
  { username: 'phanphuhien', name: 'Phan Phú Hiền' },
  { username: 'ledungnhat', name: 'Lê Dũng Nhật' },
  { username: 'phankhoathuy', name: 'Phan Khoa Thúy' },
  { username: 'nguyenyenhan', name: 'Nguyễn Yến Hân' },
  { username: 'phandungtu', name: 'Phan Dũng Tú' },
  { username: 'danghuyentan', name: 'Đặng Huyền Tân' },
  { username: 'danganhthuy', name: 'Đặng Anh Thúy' },
  { username: 'hohuonghieu', name: 'Hồ Hương Hiếu' },
  { username: 'phamthuyviet', name: 'Phạm Thúy Việt' },
  { username: 'hohungcong', name: 'Hồ Hùng Công' },
  { username: 'phamhungngan', name: 'Phạm Hùng Ngân' },
  { username: 'tranthinhat', name: 'Trần Thị Nhật' },
  { username: 'hohuykien', name: 'Hồ Huy Kiên' },
  { username: 'leanhthinh', name: 'Lê Anh Thịnh' },
  { username: 'trankhoahien', name: 'Trần Khoa Hiền' },
  { username: 'hoangtrunghien', name: 'Hoàng Trung Hiền' },
  { username: 'phamduyenhuong', name: 'Phạm Duyên Hương' },
  { username: 'nguyentrungdong', name: 'Nguyễn Trung Đông' },
  { username: 'buihoatruong', name: 'Bùi Hòa Trường' },
  { username: 'daoyentung', name: 'Đào Yến Tùng' },
  { username: 'vuduyenhien', name: 'Vũ Duyên Hiền' },
  { username: 'vuphuthuy', name: 'Vũ Phú Thúy' },
  { username: 'phamhoakhoi', name: 'Phạm Hòa Khôi' },
  { username: 'leminhtuan', name: 'Lê Minh Tuấn' },
  { username: 'phantrungnhat', name: 'Phan Trung Nhật' },
  { username: 'lengoctrang', name: 'Lê Ngọc Trang' },
  { username: 'trannhuhuong', name: 'Trần Như Hương' },
  { username: 'trananhnhat', name: 'Trần Anh Nhật' },
  { username: 'hoanganhthuy', name: 'Hoàng Anh Thúy' },
  { username: 'letrungtien', name: 'Lê Trung Tiến' },
  { username: 'vuhieuminh', name: 'Vũ Hiếu Minh' },
  { username: 'buithanhcong', name: 'Bùi Thành Công' },
  { username: 'nguyenvanhai', name: 'Nguyễn Văn Hải' },
  { username: 'tranngannhat', name: 'Trần Ngân Nhật' },
  { username: 'nguyenminhtien', name: 'Nguyễn Minh Tiến' },
  { username: 'tranyentrang', name: 'Trần Yến Trang' },
  { username: 'hoangminhhung', name: 'Hoàng Minh Hùng' },
  { username: 'dangphuthuy', name: 'Đặng Phú Thúy' },
  { username: 'tranthuykhoi', name: 'Trần Thuý Khôi' },
  { username: 'buitungtung', name: 'Bùi Tùng Tùng' },
  { username: 'dangthaiphu', name: 'Đặng Thái Phú' },
  { username: 'dangtrangdieu', name: 'Đặng Trang Diệu' },
  { username: 'tranthaitam', name: 'Trần Thái Tâm' },
  { username: 'dangtientrang', name: 'Đặng Tiến Trang' },
  { username: 'hoangthaihoan', name: 'Hoàng Thái Hoàn' },
  { username: 'daothanhdieu', name: 'Đào Thành Diệu' },
  { username: 'nguyenphuhuong', name: 'Nguyễn Phú Hương' },
  { username: 'nguyenminhthuy', name: 'Nguyễn Minh Thúy' },
  { username: 'dangquochai', name: 'Đặng Quốc Hải' },
  { username: 'phanyenhien', name: 'Phan Yến Hiền' },
  { username: 'hothitan', name: 'Hồ Thị Tân' },
  { username: 'nguyenhaiviet', name: 'Nguyễn Hải Việt' },
  { username: 'hoductruong', name: 'Hồ Đức Trường' },
  { username: 'buitunghan', name: 'Bùi Tùng Hân' },
  { username: 'buithuycong', name: 'Bùi Thuý Công' },
  { username: 'vuminhkhoi', name: 'Vũ Minh Khôi' },
  { username: 'daongannhat', name: 'Đào Ngân Nhật' },
  { username: 'ledungthien', name: 'Lê Dũng Thiên' },
  { username: 'phamthanhtam', name: 'Phạm Thành Tâm' },
  { username: 'daokhoatruong', name: 'Đào Khoa Trường' },
  { username: 'vudungtrang', name: 'Vũ Dũng Trang' },
  { username: 'phanthuydong', name: 'Phan Thuý Đông' },
  { username: 'hoduyenhien', name: 'Hồ Duyên Hiền' },
  { username: 'hothukien', name: 'Hồ Thu Kiên' },
  { username: 'buihunganh', name: 'Bùi Hùng Anh' },
  { username: 'vuyenkhoi', name: 'Vũ Yến Khôi' },
  { username: 'buihaidieu', name: 'Bùi Hải Diệu' },
  { username: 'buinganhuong', name: 'Bùi Ngân Hương' },
  { username: 'hoangthuytruong', name: 'Hoàng Thuý Trường' },
  { username: 'hohuyentung', name: 'Hồ Huyền Tùng' },
  { username: 'trannhucong', name: 'Trần Như Công' },
  { username: 'hoyentung', name: 'Hồ Yến Tùng' },
  { username: 'hoangthuyphu', name: 'Hoàng Thúy Phú' },
  { username: 'phananhthien', name: 'Phan Anh Thiên' },
  { username: 'daothukhoi', name: 'Đào Thu Khôi' },
  { username: 'lehungmai', name: 'Lê Hùng Mai' },
  { username: 'lehaihuong', name: 'Lê Hải Hương' },
  { username: 'daotrungtien', name: 'Đào Trung Tiến' },
  { username: 'trantungngan', name: 'Trần Tùng Ngân' },
  { username: 'nguyenkhoadat', name: 'Nguyễn Khoa Đạt' },
  { username: 'buimailam', name: 'Bùi Mai Lâm' },
  { username: 'nguyennhutrang', name: 'Nguyễn Như Trang' },
  { username: 'daotrangnhat', name: 'Đào Trang Nhật' },
  { username: 'phamngoctam', name: 'Phạm Ngọc Tâm' },
  { username: 'daohaihan', name: 'Đào Hải Hân' },
  { username: 'hoanghungviet', name: 'Hoàng Hùng Việt' },
  { username: 'hongockien', name: 'Hồ Ngọc Kiên' },
  { username: 'phantientam', name: 'Phan Tiến Tâm' },
  { username: 'daovanhuong', name: 'Đào Văn Hương' },
  { username: 'tranhuyennhat', name: 'Trần Huyền Nhật' },
  { username: 'dangtuandong', name: 'Đặng Tuấn Đông' },
  { username: 'hoangtrangminh', name: 'Hoàng Trang Minh' },
  { username: 'hoanghangnhat', name: 'Hoàng Hằng Nhật' },
  { username: 'tranthaitrang', name: 'Trần Thái Trang' },
  { username: 'tranthutien', name: 'Trần Thu Tiến' },
  { username: 'phanthumai', name: 'Phan Thu Mai' },
  { username: 'hominhtam', name: 'Hồ Minh Tâm' },
  { username: 'lengochien', name: 'Lê Ngọc Hiền' },
  { username: 'phantrunghuong', name: 'Phan Trung Hương' },
  { username: 'vutrunghai', name: 'Vũ Trung Hải' },
  { username: 'builinhtu', name: 'Bùi Linh Tú' },
  { username: 'daongocmai', name: 'Đào Ngọc Mai' },
  { username: 'hoangdungmai', name: 'Hoàng Dũng Mai' },
  { username: 'nguyenngochieu', name: 'Nguyễn Ngọc Hiếu' },
  { username: 'hotuannam', name: 'Hồ Tuấn Nam' },
  { username: 'daohuongtrang', name: 'Đào Hương Trang' },
  { username: 'tranhieuthien', name: 'Trần Hiếu Thiên' },
  { username: 'hominhlam', name: 'Hồ Minh Lâm' },
  { username: 'dangminhhien', name: 'Đặng Minh Hiền' },
  { username: 'nguyenhungkien', name: 'Nguyễn Hùng Kiên' },
  { username: 'nguyenhuykien', name: 'Nguyễn Huy Kiên' },
  { username: 'vuthinhthuy', name: 'Vũ Thịnh Thúy' },
  { username: 'dangthuyhan', name: 'Đặng Thúy Hân' },
  { username: 'buihangtam', name: 'Bùi Hằng Tâm' },
  { username: 'tranthuythinh', name: 'Trần Thúy Thịnh' },
  { username: 'daothanhnha', name: 'Đào Thành Nhã' },
  { username: 'danghaitien', name: 'Đặng Hải Tiến' },
  { username: 'phamdunghung', name: 'Phạm Dũng Hùng' },
  { username: 'phanthudieu', name: 'Phan Thu Diệu' },
  { username: 'leminhhuong', name: 'Lê Minh Hương' },
  { username: 'nguyennhuthuy', name: 'Nguyễn Như Thúy' },
  { username: 'tranduyennhat', name: 'Trần Duyên Nhật' },
  { username: 'danghieuhan', name: 'Đặng Hiếu Hân' },
  { username: 'vuthingan', name: 'Vũ Thị Ngân' },
  { username: 'daothuhan', name: 'Đào Thu Hân' },
  { username: 'phanmaidieu', name: 'Phan Mai Diệu' },
  { username: 'nguyenthinhnha', name: 'Nguyễn Thịnh Nhã' },
  { username: 'lethuyhuong', name: 'Lê Thúy Hương' },
  { username: 'hoangthuquoc', name: 'Hoàng Thu Quốc' },
  { username: 'hoanghoahuong', name: 'Hoàng Hòa Hương' },
  { username: 'dangtrungkien', name: 'Đặng Trung Kiên' },
  { username: 'nguyenhungnha', name: 'Nguyễn Hùng Nhã' },
  { username: 'letuantam', name: 'Lê Tuấn Tâm' },
  { username: 'vutuanquoc', name: 'Vũ Tuấn Quốc' },
  { username: 'tranthuyanh', name: 'Trần Thúy Anh' },
  { username: 'tranthutam', name: 'Trần Thu Tâm' },
  { username: 'buiphuhuong', name: 'Bùi Phú Hương' },
  { username: 'nguyentunganh', name: 'Nguyễn Tùng Anh' },
  { username: 'buihuynhat', name: 'Bùi Huy Nhật' },
  { username: 'danghieukhoi', name: 'Đặng Hiếu Khôi' },
  { username: 'hodunghan', name: 'Hồ Dũng Hân' },
  { username: 'phamhungmai', name: 'Phạm Hùng Mai' },
  { username: 'phanthuythuy', name: 'Phan Thúy Thúy' },
  { username: 'buithuytung', name: 'Bùi Thuý Tùng' },
  { username: 'dangtrangkien', name: 'Đặng Trang Kiên' },
  { username: 'hoangngocphu', name: 'Hoàng Ngọc Phú' },
  { username: 'hoanglinhhien', name: 'Hoàng Linh Hiền' },
  { username: 'phamhuyenquoc', name: 'Phạm Huyền Quốc' },
  { username: 'letungquoc', name: 'Lê Tùng Quốc' },
  { username: 'hohaitam', name: 'Hồ Hải Tâm' },
  { username: 'nguyenminhhieu', name: 'Nguyễn Minh Hiếu' },
  { username: 'tranhuyenmai', name: 'Trần Huyền Mai' },
  { username: 'vuhungtam', name: 'Vũ Hùng Tâm' },
  { username: 'buithanhdat', name: 'Bùi Thành Đạt' },
  { username: 'vuhuongtuan', name: 'Vũ Hương Tuấn' },
  { username: 'hoangtienviet', name: 'Hoàng Tiến Việt' },
  { username: 'phamtientam', name: 'Phạm Tiến Tâm' },
  { username: 'tranthinhhien', name: 'Trần Thịnh Hiền' },
  { username: 'phanminhdieu', name: 'Phan Minh Diệu' },
  { username: 'hoanhtam', name: 'Hồ Anh Tâm' },
  { username: 'lehaitam', name: 'Lê Hải Tâm' },
  { username: 'phamthuytung', name: 'Phạm Thuý Tùng' },
  { username: 'buithuytien', name: 'Bùi Thuý Tiến' },
  { username: 'lenganhuong', name: 'Lê Ngân Hương' },
  { username: 'tranthuydieu', name: 'Trần Thuý Diệu' },
  { username: 'leyentu', name: 'Lê Yến Tú' },
  { username: 'phanhieuhien', name: 'Phan Hiếu Hiền' },
  { username: 'dangvandieu', name: 'Đặng Văn Diệu' },
  { username: 'nguyentienthien', name: 'Nguyễn Tiến Thiên' },
  { username: 'vutrungnhat', name: 'Vũ Trung Nhật' },
  { username: 'phanquoctien', name: 'Phan Quốc Tiến' },
  { username: 'hoanghaiphu', name: 'Hoàng Hải Phú' },
  { username: 'hoangkhoacong', name: 'Hoàng Khoa Công' },
  { username: 'phanhuyenhien', name: 'Phan Huyền Hiền' },
  { username: 'vuhuyentan', name: 'Vũ Huyền Tân' },
  { username: 'danghieuhieu', name: 'Đặng Hiếu Hiếu' },
  { username: 'lehunglam', name: 'Lê Hùng Lâm' },
  { username: 'nguyenhunglam', name: 'Nguyễn Hùng Lâm' },
  { username: 'nguyentrangtien', name: 'Nguyễn Trang Tiến' },
  { username: 'vuminhmai', name: 'Vũ Minh Mai' },
  { username: 'honhuhuong', name: 'Hồ Như Hương' },
  { username: 'trantrangkien', name: 'Trần Trang Kiên' },
  { username: 'vuhuytrang', name: 'Vũ Huy Trang' },
  { username: 'lehunghuong', name: 'Lê Hùng Hương' },
  { username: 'danghungnha', name: 'Đặng Hùng Nhã' },
  { username: 'lethaithuy', name: 'Lê Thái Thúy' },
  { username: 'ledungthuy', name: 'Lê Dũng Thúy' },
  { username: 'hoangthinhdieu', name: 'Hoàng Thịnh Diệu' },
  { username: 'hoangtungdong', name: 'Hoàng Tùng Đông' },
  { username: 'phamlinhnhat', name: 'Phạm Linh Nhật' }
]

const createRandomPost = () => {
  const number = Math.floor(Math.random() * medias.length)

  const posts: PostReqBody = {
    type: PostType.Post,
    audience: PostAudience.Everyone,
    content: faker.lorem.paragraph({ min: 20, max: 40 }),
    hashtags: [],
    mentions: [],
    medias: [medias[number]],
    parent_id: null
  }
  return posts
}

const users: RegisterReqBody[] = faker.helpers.multiple(createRandomUser, { count: USER_COUNT })

const insertMultipleUsers = async (users: RegisterReqBody[]) => {
  const result = await Promise.all(
    users.map(async (user, index) => {
      console.log(index)
      const user_id = new ObjectId()
      const numberAvatars = Math.floor(Math.random() * avatars.length)
      await databaseServices.users.insertOne(
        new User({
          ...user,
          _id: user_id,
          avatar: avatars[numberAvatars],
          post_circle: [user_id],
          username: names[index].username,
          name: names[index].name,
          password: hasPassword(user.password),
          date_of_birth: new Date(user.date_of_birth),
          verify: UserVerifyStatus.Verified
        })
      )
      return user_id
    })
  )
  return result
}

const followMultipleUsers = async (user_id: string, followed_user_ids: ObjectId[]) => {
  await Promise.all(
    followed_user_ids.map((followed_user_id) => {
      databaseServices.followers.insertOne(
        new Follower({
          user_id: new ObjectId(user_id),
          followed_user_id: new ObjectId(followed_user_id)
        })
      )
      databaseServices.followers.insertOne(
        new Follower({
          user_id: new ObjectId(followed_user_id),
          followed_user_id: new ObjectId(user_id)
        })
      )
    })
  )
}

const insertMultiplePost = async (ids: ObjectId[]) => {
  let count = 0
  const result = await Promise.all(
    ids.map(async (id, index) => {
      await Promise.all([
        postsService.createPost(id.toString(), createRandomPost()),
        postsService.createPost(id.toString(), createRandomPost())
      ])
      count += 2
      console.log(`Create ${count} posts`)
    })
  )
  return result
}

insertMultipleUsers(users).then((ids) => {
  followMultipleUsers(MY_ID, ids)
  insertMultiplePost(ids)
})
